# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog,
# values which you are expected to set up once and rarely edit after that.
# If you find yourself editing this file very often, consider using
# Jekyll's data files feature for the data you need to update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when
# you use 'bundle exec jekyll serve'. If you change this file, please
# restart the server process.

# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
title: Roomkey Deep Dream Art
description: >-
  These art pieces were created as part of a hack-a-thon at Roomkey. The art was
  created using a combination of multiple passes through the Deep Dream
  Generator and then final tweaking in Photoshop.
baseurl: "/a-frame-art-gallery"
url: ""
github_username: AgentO3

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Configure collections
collections:
  artworks:
    output: true
  rooms:
    output: true

# Default values for collections
defaults:
  - scope:
      path: ""
      type: "rooms"
    values:
      layout: "rooms"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
